# StVO-PL options
# -----------------------------------------------------------------------------------------------------
has_points         : true      # true if using points
has_lines          : true      # true if using line segments
lr_in_parallel     : true      # true if detecting and matching features in parallel
pl_in_parallel     : true      # true if detecting points and line segments in parallel

# Tracking parameters
# -----------------------------------------------------------------------------------------------------
# Point features
min_ratio_12_p    : 0.75       # min. ratio between the first and second best matches
# Line segment features
min_ratio_12_l    : 0.75       # parameter to avoid outliers in line matching

# Optimization parameters
# -----------------------------------------------------------------------------------------------------
inlier_k         : 4.0         # factor to discard outliers before the refinement stage

# Feature detection parameters
# -----------------------------------------------------------------------------------------------------
# ORB detector
orb_nfeatures    : 1200        # number of ORB features to detect
orb_nlevels      : 4           # number of pyramid levels
orb_fast_th      : 20          # default FAST threshold
# LSD parameters
lsd_nfeatures    : 300         # number of LSD lines detected (set to 0 if keeping all lines)
